// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9bPs0vPdkS7XC9aL-fJHzb-b6VofvXBI',
    appId: '1:553354265917:web:b8a9530d8fd3f19c0eb154',
    messagingSenderId: '553354265917',
    projectId: 'local-news-app-451a0',
    authDomain: 'local-news-app-451a0.firebaseapp.com',
    storageBucket: 'local-news-app-451a0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABIPuqZG-QeLiLz4lMk3MX-73bzbDb_oo',
    appId: '1:553354265917:android:6f4d119104044f4c0eb154',
    messagingSenderId: '553354265917',
    projectId: 'local-news-app-451a0',
    storageBucket: 'local-news-app-451a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjONolT8pd0zXcO9AXWV6PEG6rTyKONrA',
    appId: '1:553354265917:ios:cfea45380c29a73c0eb154',
    messagingSenderId: '553354265917',
    projectId: 'local-news-app-451a0',
    storageBucket: 'local-news-app-451a0.firebasestorage.app',
    iosBundleId: 'com.example.localnewsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjONolT8pd0zXcO9AXWV6PEG6rTyKONrA',
    appId: '1:553354265917:ios:cfea45380c29a73c0eb154',
    messagingSenderId: '553354265917',
    projectId: 'local-news-app-451a0',
    storageBucket: 'local-news-app-451a0.firebasestorage.app',
    iosBundleId: 'com.example.localnewsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9bPs0vPdkS7XC9aL-fJHzb-b6VofvXBI',
    appId: '1:553354265917:web:bd235ffcb6409e6c0eb154',
    messagingSenderId: '553354265917',
    projectId: 'local-news-app-451a0',
    authDomain: 'local-news-app-451a0.firebaseapp.com',
    storageBucket: 'local-news-app-451a0.firebasestorage.app',
  );
}
